version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
      - ./VERSION:/usr/src/app/VERSION
      - ./src/package.json:/usr/src/app/package.json
      - ./src/package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules
    command: npm run dev
    env_file:
      - .env.development
