version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon --legacy-watch index.js
    env_file:
      - .env.development
