# Use the official Node.js image as a base
FROM node:14

# Create and set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the application files
COPY . .

# Install nodemon globally for development
RUN npm install -g nodemon

# Command to run the application with nodemon
CMD ["nodemon", "--legacy-watch", "src/index.js"]
