version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build Docker Image
          command: docker build -t your-dockerhub-username/your-repo-name .
      - run:
          name: Test Docker Image
          command: docker run -d -p 3000:3000 your-dockerhub-username/your-repo-name
      - run:
          name: Run Tests
          command: |
            sleep 10
            curl -f http://localhost:3000

  deploy:
    docker:
      - image: circleci/node:14

    steps:
      - setup_remote_docker
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/your-repo-name:latest .
            docker push $DOCKER_USERNAME/your-repo-name:latest
      - run:
          name: Deploy to Kubernetes
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $KUBERNETES_CLUSTER_NAME
            kubectl set image deployment/your-repo-name your-repo-name=$DOCKER_USERNAME/your-repo-name:latest --record

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
