name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Extract version
        id: get_version
        run: echo "::set-output name=version::$(cat src/VERSION)"

      - name: Build and push Docker image
        run: |
          VERSION=$(cat src/VERSION)
          docker buildx build --platform linux/arm/v7 -t inamdryermaster/beaglebone-app:${VERSION} --push -f Dockerfile .
          docker buildx build --platform linux/arm/v7 -t inamdryermaster/beaglebone-app:latest --push -f Dockerfile .
